spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: poc_webflux
      port: 27017
      host: localhost
  thymeleaf:
    reactive:
      chunked-mode-view-names:
        -list-chunk
      max-chunk-size:
        512

