spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: poc_webflux
      port: 27017
      host: localhost

client:
  base:
    pokemon: https://pokeapi.co/api/v2/pokemon